baseURL = "https://elliberes.me"
languageCode = "en-us"
title = "Elli Beres"
theme = "cactus"
copyright = "Elli Beres"


summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About Me"
url = "/about"
weight = 2

[[menu.main]]
name = "My Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Digital Garden"
url = "https://elliberes.me/digitalgarden/"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = 'catppuccin-latte'
    tabWidth = 4

[params]

  colortheme = "light" # dark, light, white, or classic
  rss = true
  showAllPostsArchive = false

  # Home page settings
  description = """
  ```yaml
    ---
    name: 'Elli'
        in Greek: 'Έλλη'
        short for: 'Eleftheria'
            in Greek: 'Ελευθερία'
    pronouns: '(she/her/hers)'
  ```
  """
  aboutMe = """
  ```yaml
    ---
    position: 'Undergraduate Student Researcher'
        - research_group: 'Xenobot Lab'
          location: 'Northwestern University'
        - research_group: 'Leonard Lab'
          location: 'Northwestern University'
    education:
        - degree: 'BS in Computer Science'
          institution: 'Northwestern University'
          graduation_date: 'Jun 2025'
        - degree: 'MS in Computer Engineering'
          institution: 'Northwestern University'
          graduation_date: 'Jun 2025'
    interested_in:
        - 'machine learning'
        - 'artificial intelligence'
        - 'building embedded and decentralized systems that are'
            - 'safer'
            - 'more secure'
            - 'more sustainable'
            - 'more equitable'
            - 'more accessible'
            - 'more intelligent'
    supporter_of:
        - 'free and open-source software (FOSS)'
        - 'technological decentralization'
        - 'solarpunk'
  ```
  """
  aboutMeSection = "about"
  aboutMeSectionTitle = "More about me!"

  writingSection = "posts"
  writingSectionTitle = "Check out all my posts!"
  writingTagsTitle = "Or look at a specific topic."
  tagsOverview = true
  
  showProjectsList = true
  projectsUrl = "https://github.com/ellifteria" # title link for projects list
  projectsTitle = "Check out some of my projects here!"
  
  showPublicationsList = true
  # publicationsUrl = "https://github.com/ellifteria" # title link for projects list
  publicationsTitle = "Here are my publications!"
  paperssSubTitle = "Papers:"
  postersSubTitle = "Posters:"
  
  beliefsDescription = """
  ```yaml
    ---
    - 'love is love'
    - 'trans rights are human rights'
    - 'feminism is for everyone'
    - 'there is no planet B'
    - 'science is real'
    - 'black lives matter'
  ```
  """
  

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02"

  # Post page settings
  show_updated = true
  showReadTime = true

  [params.comments]
    enabled = false

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/ellifteria"
  [[params.social]]
    name = "mastodon"
    link = "https://fosstodon.org/@ellifteria"
  [[params.social]]
    name = "email"
    link = "elliberes@skiff.com"  # no need for "mailto:" in the head
